### PR TITLE
Run composer update to sync new dependencies

### PR DESCRIPTION
**Pull request by carusogabriel**
Found it at #13 https://travis-ci.org/doctrine/reflection/jobs/433235770

### CODE REVIEW

**Comment by Ocramius** [comment]
Could you please rebase this to verify the build?

**Comment by carusogabriel** [comment]
@Ocramius Already did:

```sh
e4286e5 (HEAD -> composer-update, origin/composer-update) Run composer update to sync new dependencies
ca1b0e4 (upstream/master, master) Merge pull request #13 from carusogabriel/doctrine-cs-v5
093041f (origin/doctrine-cs-v5) Apply Doctrine CS v5

```

**Review by Ocramius — APPROVED** [review]
:ship:

**Comment by Majkl578** [comment]
Do we really need PRs like this? I mean, the lock file is for CS and SA only and this update updated neither of those.

**Comment by jwage** [comment]
The build was failing because of this in https://github.com/doctrine/reflection/pull/13 That is why we made the PR, to fix it.

**Pull request merged**
