### PR TITLE
Add conflict on doctrine/common for <2.9@dev

### PR DESCRIPTION
**Pull request by jwage**

### CODE REVIEW

**Review by Majkl578 — APPROVED** [review]

**Comment by Majkl578** [comment]
The build failure is obvious, there is no 2.9.0 now. :) So we either need 2.9@dev in require-dev or wait...

**Comment by Ocramius** [comment]
Merging this anyway, as we can't release without this conflict, and `doctrine/common` releasing will happen after this release anyway.

**Comment by Ocramius** [comment]
@Majkl578 `1.0.1` the correct target release? Since we are changing dependencies, this should probably be `1.1.0`

**Comment by Majkl578** [comment]
It was forgotten in 1.0.0 so it should be considered a bugfix. Otherwise there may be weird composer errors with optimized autoloader (ambiguous class resolution with Common 2.8 + this package). :/

**Comment by Ocramius** [comment]
@Majkl578 the problem is that this kind of approach makes `1.0.0` installable (and a fallback), which means many tricky scenarios where the SAT fails everywhere but for `1.0.0`, and it will install `1.0.0` even if newer versions are available.

Annoying, but I understand that this was forgotten: happens.

**Comment by Majkl578** [comment]
Yup, suggestions? :) I don't feel like retag would be a cool solution. So at least reflection is not a package that is usually used without persistence so conflict in persistence should hold installation back.

**Comment by Ocramius** [comment]
Tagging `1.0.1` and making sure nothing else uses `1.0.0` is a decent mitigation. This means there's no released `doctrine/common` version pointing at `1.0.0`

**Comment by jwage** [comment]
@Ocramius @Majkl578 want me to go ahead and tag 1.0.1 of doctrine/reflection?

**Comment by Majkl578** [comment]
Not sure, we are in a deadlock right now. :) Common 2.9 will need ^1.0.1 and 1.0.1 here needs Common 2.9 (require-dev).

**Comment by jwage** [comment]
Then we can just do 2 releases. Release 1.0.1 here now. Update common to 1.0.1, then release 1.0.2 to reference common 2.9

**Pull request merged**
