### PR TITLE
Manually merge 1.2.x into master

### PR DESCRIPTION
**Pull request by greg0ire**

### CODE REVIEW

**Comment by greg0ire** [comment]
I just removed the Scrutinizer webhook from the settings after seeing it here.

**Comment by SenseException** [comment]
Do you need to rebase your branch?

**Comment by greg0ire** [comment]
@SenseException I don't this is a merge up. I just need somebody to approve the local merge I did so that I can push this branch to `origin`

**Comment by greg0ire** [comment]
Ah apparently I don't… it worked.

**Pull request merged**
