### PR TITLE
Validate composer json

### PR DESCRIPTION
**Pull request by greg0ire**

### CODE REVIEW

**Review by PReimers — COMMENTED** [review]
LGTM

**Review by beberlei — APPROVED** [review]

**Comment by beberlei** [comment]
@greg0ire I believe its not needed in 1.2.x, because composer can guess the branch here.

**Comment by greg0ire** [comment]
You are right, at first I had wrongly targeted master

**Comment by greg0ire** [comment]
> @greg0ire I believe its not needed in 1.2.x, because composer can guess the branch here.

@beberlei I'm not sure anymore. Can you check the scrutinizer failure? It seems related.

**Comment by greg0ire** [comment]
From the message, it's clearly related, I'm going to cherry-pick your commit again

**Comment by greg0ire** [comment]
Oh wait I just have to rebase in fact.

**Comment by greg0ire** [comment]
Or just merge since your commit is already in 1.2.x

**Pull request merged**
