### PR TITLE
Allow PHP 8

### PR DESCRIPTION
**Pull request by greg0ire**

### CODE REVIEW

**Comment by greg0ire** [comment]
> ........PHP Fatal error:  Declaration of Doctrine\Common\Reflection\StaticReflectionClass::newInstance($args) must be compatible with ReflectionClass::newInstance(...$args) in /home/travis/build/doctrine/reflection/lib/Doctrine/Common/Reflection/StaticReflectionClass.php on line 377

Ah there is a noteworthy failure

**Comment by greg0ire** [comment]
@alcaeus not sure what to do… something like https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/PhpUnit/CoverageListener.php maybe? Or are there preloading-related issues with this?

**Comment by ostrolucky** [comment]
It's not a big bc break. Would be breaking only for people extending our class. I would say just document minor bc break and do the change

**Comment by greg0ire** [comment]
> Would be breaking only for people extending our class.

If they also override that method (that currently throws an exception). I think you are right.

**Comment by andypost** [comment]
What's state of this PR? Looks changes in codebase still needed https://github.com/doctrine/reflection/issues/46#issuecomment-703944997

**Comment by greg0ire** [comment]
IMO the whole repo is going to be deprecated, so if you are using it you should consider alternatives.

**Comment by catch56** [comment]
Drupal 9 is using Doctrine reflection, and will be supported until the end of 2023 (i.e. around the same time that Symfony 4 goes out of support). While we can certainly look at moving away from it, it would be a lot more straightforward if we dropped the dependency for Drupal 10.

**Comment by alexpott** [comment]
I've created #49 that attempts to allow doctrine/reflection on PHP 8. It'd be really great if we could keep this dependency for the Drupal 9 lifecycle. It'd give us and the rest of the community time to switch to alternatives.

**Comment by greg0ire** [comment]
Closing in favor of #49

**Comment by greg0ire** [comment]
@alexpott I think we can still review PRs and merge them, not sure when we will mark this as abandoned, but do plan a move.

**Pull request closed without merging**
