### PR TITLE
Update branch metadata

### PR DESCRIPTION
**Pull request by greg0ire**
- alias master to 1.3.x
- mark 1.2.x as current and stable
- mark 1.1.x as no longer maintained

### CODE REVIEW

**Review by SenseException — APPROVED** [review]

**Review by SenseException — CHANGES_REQUESTED** [review]
composer.lock isn't updated to the latest changes. Scrutinizer is right this time.

**Review by SenseException — APPROVED** [review]

**Review by alcaeus — APPROVED** [review]
Changes LGTM, but haven't checked CI status ;)

**Comment by greg0ire** [comment]
It's related to `COMPOSER_ROOT_PACKAGE` I think, should work after a merge up.

**Comment by greg0ire** [comment]
I merged #39, let's restart this one.

**Comment by greg0ire** [comment]
Super green :)

**Pull request merged**
