### PR TITLE
Allow `doctrine/annotations` v2

### PR DESCRIPTION
**Pull request by boesing**

### CODE REVIEW

**Comment by boesing** [comment]
FYI: There is no 1.3.x branch and thus had to target 1.2.x

Moving to `roave/better-reflection` is not a real option as it lacks support for use statements as far as I can see.
Or am I just unable to find it? :-/

**Comment by greg0ire** [comment]
> Moving to roave/better-reflection is not a real option as it lacks support for use statements as far as I can see.

What do you mean?

**Comment by boesing** [comment]
one of the key features of this library (we are using) is to parse use Statements to get annotation types correct. 

I did not see this feature within better-reflection as it does not really extend the php reflection but provides almost the same feature set.

**Comment by derrabus** [comment]
> is not a real option

But using an abandoned library is? 🙈 🙉

**Review by derrabus — APPROVED** [review]

**Comment by derrabus** [comment]
Released as 1.2.4.

**Comment by boesing** [comment]
> > is not a real option
> 
> But using an abandoned library is? 🙈 🙉

Nope, I already work on removing it from our usage but still thought its worth a try to provide a patch as it seems that with 40k monthly installs this component is still heavily in use 😅

**Comment by greg0ire** [comment]
We're trying to get that number down, not up :sweat: 

And if I understand what you are saying, you're saying that you are not sure that this piece of code does not work:

```php
use Some\RandomClass;

Roave\Reflection::reflectClassOrWhateverTheActualApiIs(RandomClass::class);
```

Because I find that highly unlikely. 

> as far as I can see

as far as you can see by reading the readme, or as far as you tried by installing the library and trying it out on a sample file?

**Comment by greg0ire** [comment]
Here is an example of `BetterReflection` reflecting itself:

```
<?php

require_once 'vendor/autoload.php';

use Roave\BetterReflection\BetterReflection;

var_dump((new BetterReflection())
    ->reflector()
    ->reflectClass(BetterReflection::class)->getName());
```

It prints `string(39) "Roave\BetterReflection\BetterReflection"`

**Comment by boesing** [comment]
```php

namespace Foo;

use Bar\Baz as Qoo;

class Foo
{
    /** @var Qoo */
    public $qoo;
}
```

With this library, I can find out what type the property is. With better reflection its not possible.

**Comment by greg0ire** [comment]
But this works though:

```php
<?php

require_once 'vendor/autoload.php';

use Roave\BetterReflection\BetterReflection as Qoo;

class Foo
{
    public Qoo $qoo;
}

var_dump((new Qoo())
    ->reflector()
    ->reflectClass(Foo::class)->getProperty('qoo')->getType()->getName());
```

So the use statement is resolved. I think what is not supported is phpdoc reflection when using aliases, and that's quite different.

It does not appear to work without the alias either, and you have to install v4 of the library to even be able to use docblocks right? So I hope you have a plan to switch to typed properties because support for reading phpdoc has been removed from roave in v5, which means this won't get fixed ever.

That being said, if  look at the code, I can find in v4 this test: https://github.com/Roave/BetterReflection/blob/0581939b89e22d80dfef3b988efaefbfc39b05b3/test/unit/TypesFinder/FindParameterTypeTest.php#L52-L74

With that and this markdown, https://github.com/Roave/BetterReflection/blob/4.12.x/docs/usage.md

I was able to piece together the following:

```php
<?php

require_once 'vendor/autoload.php';

use Roave\BetterReflection\BetterReflection;
use Roave\BetterReflection\Reflector\ClassReflector;
use Roave\BetterReflection\SourceLocator\Type\StringSourceLocator;

$php = '<?php
namespace Foo;

use Bar\Baz as Qoo;

class Foo
{
    /** @var Qoo */
    public $qoo;
};';

$astLocator = (new BetterReflection())->astLocator();
$property = (new ClassReflector(new StringSourceLocator($php, $astLocator)))
    ->reflect('Foo\Foo')
    ->getProperty('qoo');

var_dump($property->getDocBlockTypeStrings());
```


It prints

```
array(1) {
  [0]=>
  string(8) "\Bar\Baz"
}
```

So… I guess you should be able to do something from that.

**Pull request merged**
