### PR TITLE
Fix PHP 8.1 deprecations for tentative return types

### PR DESCRIPTION
**Pull request by Sweetchuck**
Issue #56 - PHP 8.1 compatibility

### CODE REVIEW

**Comment by derrabus** [comment]
Thank you for your PR. Can you please fix the CS issues?

Also note that we don't really maintain this package anymore. You should migrate to a different library if that's possible for you.

**Comment by derrabus** [comment]
Ah no, you can't really fix the CS issues. The tooling is outdated. I'll take care of that in a follow-up.

**Review by derrabus — APPROVED** [review]

**Comment by derrabus** [comment]
Thank you.

**Comment by derrabus** [comment]
You missed a couple of spots. 😅 

Follow-up: #58

**Comment by Sweetchuck** [comment]
`composer why doctrine/reflection`
> drupal/core              9.3.14  requires  doctrine/reflection (^1.1)

It is not up to me to migrate to a different library. :-)

But, it is strange to me why I am the first one who run into this problem :-)

Thank you for the quick merge.

**Comment by derrabus** [comment]
> `composer why doctrine/reflection`
> 
> > drupal/core              9.3.14  requires  doctrine/reflection (^1.1)
> 
> It is not up to me to migrate to a different library. :-)

Apparently, Drupal 10 won't require this library anymore. So you will be able to move away eventually. 🙂

**Pull request merged**
